members-only/config/routes.rb
Rails.application.routes.draw do
	root							 'static_pages#home'
	get    'signup' => 'users#new'
	get    'login'  => 'sessions#new'
	post   'login'  => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
  resources :users
  resources :posts
end

members-only/app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true
	belongs_to :user
end

members-only/app/models/user.rb
class User < ActiveRecord::Base
	before_create :assign_token
	validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 5}
	has_many :posts

	def User.create_token
		token = SecureRandom.urlsafe_base64
		digested_token = User.digest(token)
	end

	def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

	private

		def assign_token
			self.remember_token = User.create_token
		end
end

members-only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  
end

members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user, only: [:new, :create]
	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create 
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			flash[:success] = "Post created."
			redirect_to posts_path
		else
			flash[:danger] = "Problem with post."
			render 'new'
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

		def signed_in_user
			unless signed_in?
				redirect_to login_url
			end
		end

		def post_params
			params.require(:post).permit(:title, :about, :body, :user_id)
		end
end

members-only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			flash[:success] = "Thanks for signing in!"
			redirect_to root_path
		else
			flash.now[:danger] = "Invalid email/password"
			render 'new'
		end
	end

	def destroy
		log_out current_user
		redirect_to root_path
	end
end

members-only/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

members-only/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def show
	end

	def new
	end

	def create 
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

members-only/app/helpers/application_helper.rb
module ApplicationHelper
end

members-only/app/helpers/posts_helper.rb
module PostsHelper
end

members-only/app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
    remember_token = User.create_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

	def current_user=(user)
	  @current_user = user
	end

	def current_user
	  remember_token = User.digest(cookies[:remember_token])
	  @current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
	  !current_user.nil?
	end

	def log_out(user)
		user.update_attribute(:remember_token, nil)
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
		session.delete(:user_id)
		@current_user = nil
	end
end

members-only/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

members-only/app/helpers/users_helper.rb
module UsersHelper
end

members-only/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Members Only", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Posts", posts_path %> <span class="sr-only">(current)</span>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <%= link_to "#{current_user.name}", user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Log Out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign Up", new_user_path %>
          </li>
          <li>
            <%= link_to "Log In", login_path %>
          </li>
        <% end %>
        
      </ul>


        

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>

members-only/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
  	<div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

<%= yield %>

</body>
</html>

members-only/app/views/posts/index.html.erb
<div class="float-right">

<h1>Members Only Posts</h1>

<% @posts.each do |post| %>
  <h4 class="float-left"><%=post.title %></h4>  

  <% if signed_in? %>
    <p class="float-right">
      Posted by:
      <%= post.user.name %>
    </p>

  <% end %>
  <p>
    	About:
    	<%= post.about %>
    </p>
  
  <p class="clear"><%= post.body %></p>
<% end %>

<% if signed_in? %>
  <%= link_to "Create a Post", new_post_path %>
<% end %>

members-only/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :about %> <br/>
		<%= f.text_field :about %>
	</p>
	<p>
		<%= f.label :body %> <br />
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

members-only/app/views/static_pages/home.html.erb
<h1>Home</h1>

<%= link_to "Create Post", new_post_path %>